### ISSUE TITLE
How did you get the UMD dataset in this paper?

### ISSUE THREAD

**Issue by hiwmy0211** [Reagan1311/OOAL#1]
hello, thank you for your excellent work! I had a problem in getting the UMD part affordance dataset. The link given in the previous paper is "www.umiacs.umd.edu/∼amyers/part-affordance-dataset", but I click on the link shows that the page is not found. So I would like to ask if there is any way to obtain this dataset. Or can you provide this dataset? Thank you in advance for your reply!

**Comment by Reagan1311** [comment]
Hi, I use the dataset from this link: https://users.umiacs.umd.edu/~fer/affordance/part-affordance-dataset/
